# Generated by Django 6.0.2 on 2026-04-29 07:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Ex: A empresa estava com as apostilas em dia?', max_length=255)),
                ('tipo_resposta', models.CharField(choices=[('texto', 'Texto Curto'), ('texto_longo', 'Texto Longo'), ('data', 'Data (Calendário)'), ('booleano', 'Sim / Não'), ('numero', 'Número'), ('multipla_escolha', 'Múltipla Escolha (Opções)'), ('lista_suspensa', 'Lista Suspensa')], default='texto', max_length=30)),
                ('opcoes_resposta', models.CharField(blank=True, help_text='Para Múltipla Escolha ou Lista Suspensa manual. Separe por vírgula.', max_length=500, null=True)),
                ('fonte_dados', models.CharField(blank=True, help_text="Apenas para Lista Suspensa. Chave da fonte registrada em data_sources.py (ex: 'contatoes'). Deixe em branco para opções manuais.", max_length=50, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome (CDE / DDZ)')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('secretaria', models.CharField(blank=True, help_text='Ex: SEMED', max_length=150, null=True, verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'CDE / DDZ',
                'verbose_name_plural': 'CDEs / DDZs',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_consultor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cor_mapa', models.CharField(default='#3B82F6', help_text='Cor do pin no mapa (ex: #FF5733). Use um codigo hexadecimal.', max_length=7)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descrição do erro reportado pelo usuário')),
                ('device_info', models.CharField(blank=True, help_text='Informações do aparelho/OS', max_length=255, null=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], default='A', max_length=1)),
                ('frequencia_recomendada_dias', models.PositiveIntegerField(default=30)),
                ('ultima_visita', models.DateField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, help_text='Ex: -23.550520', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, help_text='Ex: -46.633308', max_length=50, null=True)),
                ('consultor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to=settings.AUTH_USER_MODEL)),
                ('consultores_autorizados', models.ManyToManyField(blank=True, related_name='empresas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='core.regiao', verbose_name='CDE / DDZ')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='contatoes', to='core.disciplina')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatoes', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Contatoes',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('relatorio', models.TextField(blank=True, help_text='Relatório preenchido pelo consultor', null=True)),
                ('nome_responsavel', models.CharField(blank=True, help_text='Nome do responsável que assinou', max_length=200, null=True)),
                ('assinatura', models.TextField(blank=True, help_text='Assinatura digitalizada em Base64', null=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('checkin_lng', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_lng', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_offline_flag', models.BooleanField(default=False, help_text='Sincronizado via cache offline')),
                ('justificativa_distancia', models.TextField(blank=True, help_text='Justificativa do Check-in fora do raio', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to=settings.AUTH_USER_MODEL)),
                ('contatoes_atendidos', models.ManyToManyField(blank=True, related_name='visitas_participadas', to='core.contato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.empresa')),
            ],
            options={
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_gerados', to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.visita')),
            ],
        ),
        migrations.CreateModel(
            name='VisitaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='visitas_fotos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.visita')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(blank=True, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perguntarelatorio')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.visita')),
            ],
            options={
                'unique_together': {('visita', 'pergunta')},
            },
        ),
    ]
