# Generated by Django 6.0.2 on 2026-04-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='regiao',
        ),
        migrations.DeleteModel(
            name='Regiao',
        ),
    ]
