# Generated by Django 5.2.12 on 2026-03-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiao',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.RemoveField(
            model_name='escola',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
