# Generated by Django 5.0.14 on 2026-03-04 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_regiao_cidade_remove_escola_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='nome_responsavel',
        ),
        migrations.AddField(
            model_name='escola',
            name='consultor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
