# Generated by Django 5.0.14 on 2026-04-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_empresa_regiao_delete_regiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa'), ('N', 'Em Negociação')], default='A', max_length=1),
        ),
        migrations.RenameModel(
            old_name='Contato',
            new_name='Funcionario',
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='core_contato',
        ),
        migrations.AlterField(
            model_name='visita',
            name='contatoes_atendidos',
            field=models.ManyToManyField(blank=True, related_name='visitas_participadas', to='core.funcionario'),
        ),
    ]
