# Generated by Django 6.0.2 on 2026-04-29 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_cnpj_cpf_alter_empresa_status_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='core.disciplina'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='core.empresa'),
        ),
    ]
