# Generated by Django 5.2.12 on 2026-03-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disciplina_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='latitude',
            field=models.CharField(blank=True, help_text='Ex: -23.550520', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='longitude',
            field=models.CharField(blank=True, help_text='Ex: -46.633308', max_length=50, null=True),
        ),
    ]
