# Generated by Django 6.0.2 on 2026-04-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_endereco_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='disciplinas',
        ),
    ]
