# Generated by Django 6.0.2 on 2026-04-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_funcionario_disciplinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='frequencia_recomendada_dias',
        ),
    ]
