# Generated by Django 5.2.12 on 2026-03-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_escola_latitude_escola_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='assinatura',
            field=models.TextField(blank=True, help_text='Assinatura digitalizada em Base64', null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='relatorio',
            field=models.TextField(blank=True, help_text='Relatório preenchido pelo consultor', null=True),
        ),
    ]
