# Generated by Django 5.2.12 on 2026-03-11 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_visita_assinatura_visita_relatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Ex: A escola estava com as apostilas em dia?', max_length=255)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='visita',
            name='checkin_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='checkin_lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='checkout_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='checkout_lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='nome_responsavel',
            field=models.CharField(blank=True, help_text='Nome do responsável que assinou', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='RespostaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(blank=True, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perguntarelatorio')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.visita')),
            ],
            options={
                'unique_together': {('visita', 'pergunta')},
            },
        ),
    ]
