# Generated by Django 6.0.2 on 2026-04-29 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_empresa_endereco_empresa_bairro_empresa_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='consultor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
    ]
