# Generated by Django 5.2.12 on 2026-03-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perguntarelatorio_visita_checkin_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntarelatorio',
            name='tipo_resposta',
            field=models.CharField(choices=[('texto', 'Texto Curto'), ('texto_longo', 'Texto Longo'), ('data', 'Data (Calendário)'), ('booleano', 'Sim / Não'), ('numero', 'Número')], default='texto', max_length=20),
        ),
    ]
