# Generated by Django 5.2.12 on 2026-03-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_perguntarelatorio_tipo_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntarelatorio',
            name='opcoes_resposta',
            field=models.CharField(blank=True, help_text='Apenas para Múltipla Escolha. Separe as opções por vírgula. Ex: A) Sim, B) Não, C) Talvez', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perguntarelatorio',
            name='tipo_resposta',
            field=models.CharField(choices=[('texto', 'Texto Curto'), ('texto_longo', 'Texto Longo'), ('data', 'Data (Calendário)'), ('booleano', 'Sim / Não'), ('numero', 'Número'), ('multipla_escolha', 'Múltipla Escolha (Opções)')], default='texto', max_length=30),
        ),
    ]
