# Generated by Django 5.0.14 on 2026-04-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_empresa_consultor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_consultor',
            new_name='is_assessor',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='consultor',
            new_name='assessor',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='consultores_autorizados',
            new_name='assessores_autorizados',
        ),
        migrations.RenameField(
            model_name='visita',
            old_name='consultor',
            new_name='assessor',
        ),
    ]
