# Generated by Django 5.0.14 on 2026-04-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_is_consultor_customuser_is_assessor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='data_conversao',
            field=models.DateField(blank=True, help_text="Data em que a empresa passou de 'Em Negociação' para 'Ativa'", null=True, verbose_name='Data de Conversão'),
        ),
    ]
