# Generated by Django 5.2.12 on 2026-03-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perguntarelatorio_opcoes_resposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiao',
            name='secretaria',
            field=models.CharField(blank=True, help_text='Ex: SEMED', max_length=150, null=True, verbose_name='Secretaria'),
        ),
    ]
