# Generated by Django 6.0.2 on 2026-04-30 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_empresa_data_conversao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('inicio_time', models.DateTimeField(auto_now_add=True)),
                ('inicio_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio_lng', models.CharField(blank=True, max_length=50, null=True)),
                ('fim_time', models.DateTimeField(blank=True, null=True)),
                ('fim_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('fim_lng', models.CharField(blank=True, max_length=50, null=True)),
                ('km_total', models.FloatField(default=0.0, help_text='Quilometragem total percorrida no dia')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada')], default='em_andamento', max_length=20)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
