# Generated by Django 5.2.12 on 2026-03-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_regiao_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
