# Generated by Django 6.0.2 on 2026-05-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jornada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreport',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Relatório de Bug', 'verbose_name_plural': 'Relatórios de Bug'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='jornada',
            options={'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='logalteracao',
            options={'verbose_name': 'Log de Alteração', 'verbose_name_plural': 'Logs de Alteração'},
        ),
        migrations.AlterModelOptions(
            name='perguntarelatorio',
            options={'verbose_name': 'Pergunta do Relatório', 'verbose_name_plural': 'Perguntas do Relatório'},
        ),
        migrations.AlterModelOptions(
            name='respostarelatorio',
            options={'verbose_name': 'Resposta do Relatório', 'verbose_name_plural': 'Respostas do Relatório'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-data', '-horario'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterModelOptions(
            name='visitafoto',
            options={'verbose_name': 'Foto da Visita', 'verbose_name_plural': 'Fotos das Visitas'},
        ),
    ]
