# Generated by Django 5.2.12 on 2026-03-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='professores_atendidos',
            field=models.ManyToManyField(blank=True, related_name='visitas_participadas', to='core.professor'),
        ),
    ]
