# Generated by Django 5.2.12 on 2026-03-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_visita_professores_atendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do ambiente ou atividade', null=True, upload_to='visitas_fotos/'),
        ),
    ]
