# Generated by Django 6.0.2 on 2026-05-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bugreport_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('periodo_relatorio_dias', models.IntegerField(default=30, help_text='Período padrão para relatórios em dias')),
                ('enviar_email_automaticamente', models.BooleanField(default=False, help_text='Enviar relatórios automaticamente via email')),
                ('frequencia_envio', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='mensal', max_length=20)),
                ('destinatarios_email', models.TextField(blank=True, help_text='Emails separados por vírgula', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Relatório',
                'verbose_name_plural': 'Configurações de Relatório',
            },
        ),
        migrations.CreateModel(
            name='RelatorioGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('resumo_geral', 'Resumo Geral'), ('performance_assessor', 'Performance do Assessor'), ('status_empresas', 'Status de Empresas'), ('conversoes', 'Taxa de Conversão'), ('visitas_detalhadas', 'Visitas Detalhadas'), ('jornadas', 'Jornadas e Quilometragem'), ('feedback_visitas', 'Feedback das Visitas'), ('comparativo_periodo', 'Comparativo de Períodos')], max_length=30)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('dados_json', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_sobre', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_gerados', to='core.empresa')),
                ('usuario_gerador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_gerados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório Gerado',
                'verbose_name_plural': 'Relatórios Gerados',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='core_relato_criado__0cee2b_idx'), models.Index(fields=['tipo', '-criado_em'], name='core_relato_tipo_00fce8_idx'), models.Index(fields=['usuario_gerador', '-criado_em'], name='core_relato_usuario_41b334_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplatePessoalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_relatorio', models.CharField(choices=[('resumo_geral', 'Resumo Geral'), ('performance_assessor', 'Performance do Assessor'), ('status_empresas', 'Status de Empresas'), ('conversoes', 'Taxa de Conversão'), ('visitas_detalhadas', 'Visitas Detalhadas'), ('jornadas', 'Jornadas e Quilometragem'), ('feedback_visitas', 'Feedback das Visitas'), ('comparativo_periodo', 'Comparativo de Períodos')], max_length=30)),
                ('filtros_padrao', models.JSONField(default=dict)),
                ('campos_incluir', models.JSONField(default=list, help_text='Lista de campos a incluir no relatório')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_relatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Personalizado',
                'verbose_name_plural': 'Templates Personalizados',
                'unique_together': {('nome', 'criador')},
            },
        ),
    ]
