# Generated by Django 6.0.2 on 2026-05-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configuracaorelatorio_relatoriogerado_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='core_funcionario',
        ),
    ]
