# Generated by Django 5.2.12 on 2026-03-13 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_visita_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='foto',
        ),
        migrations.CreateModel(
            name='VisitaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='visitas_fotos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.visita')),
            ],
        ),
    ]
