# Generated by Django 6.0.2 on 2026-05-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuracao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
