# Generated by Django 6.0.2 on 2026-03-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customuser_telefone_bugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntarelatorio',
            name='fonte_dados',
            field=models.CharField(blank=True, help_text="Apenas para Lista Suspensa. Chave da fonte registrada em data_sources.py (ex: 'professores'). Deixe em branco para opções manuais.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perguntarelatorio',
            name='opcoes_resposta',
            field=models.CharField(blank=True, help_text='Para Múltipla Escolha ou Lista Suspensa manual. Separe por vírgula.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perguntarelatorio',
            name='tipo_resposta',
            field=models.CharField(choices=[('texto', 'Texto Curto'), ('texto_longo', 'Texto Longo'), ('data', 'Data (Calendário)'), ('booleano', 'Sim / Não'), ('numero', 'Número'), ('multipla_escolha', 'Múltipla Escolha (Opções)'), ('lista_suspensa', 'Lista Suspensa')], default='texto', max_length=30),
        ),
    ]
