# Generated by Django 6.0.2 on 2026-05-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0016_delete_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='grupos_podem_alterar_responsavel',
            field=models.ManyToManyField(blank=True, related_name='configuracoes_responsavel', to='auth.group', verbose_name='Grupos que podem alterar o Responsável da visita'),
        ),
    ]
