# Generated by Django 5.0.14 on 2026-04-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_perguntarelatorio_fonte_dados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='sync_offline_flag',
            field=models.BooleanField(default=False, help_text='Sincronizado via cache offline'),
        ),
    ]
