# Generated by Django 6.0.2 on 2026-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_visita_sync_offline_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='justificativa_distancia',
            field=models.TextField(blank=True, help_text='Justificativa do Check-in fora do raio', null=True),
        ),
    ]
