# Generated by Django 6.0.2 on 2026-04-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_visita_justificativa_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cor_mapa',
            field=models.CharField(default='#3B82F6', help_text='Cor do pin no mapa (ex: #FF5733). Use um codigo hexadecimal.', max_length=7),
        ),
    ]
